config:
  warningsAsErrors: true

complexity:
  TooManyFunctions:
    ignorePrivate: true
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 170

naming:
  MatchingDeclarationName:
    active: false
